baseURL: https://gongora.xyz
languageCode: es-es
title: Rob's Life
theme: gokarna
enableRobotsTXT: true

params:
  showPostsOnHomePage: popular

menu:
  main:
    - identifier: posts
      url: /posts/
      name: Posts
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: linkedin
      url: https://linkedin.com/in/roberto_gongora
      pre: '<span data-feather="linkedin"></span>'
